all:
  # IP de votre ZiBase sur votre réseau local
  zibase_ip: 192.168.1.192
  # Informations accessibles depuis 
  # http://zibase.net/zodianet/zodiaWeb/html/zibase_login.php
  # en mode expert, rubrique SYSTEME
  # Identifiant principal de votre ZiBase
  zibase_device: ZiBASE0e0001
  # Token de votre ZiBase
  zibase_token: 21fa1234
